version: '3'
services:
  redis:
    image: redis/redis-stack:7.0.0-RC3-edge
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - redis_data:/data

  app:
    container_name: dk-server-dev
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - ./.env
    depends_on:
      - redis

volumes:
  redis_data:
